<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 8,
                'name' => 'Kashif',
                'email' => 'muhammadkashif700010@gmail.com',
                'phone_number' => NULL,
                'fcm_id' => NULL,
                'password' => '$2y$10$RLkq63RrTbMef5t5Ed2OIOCCa/3xzLbG8lO18eTLPFYiO2SkDKezG',
                'remember_token' => 'zYNuYRPMye4eUcCTSvxKKRgq4R61Yz9qvQIE6d5v6HcjuZDy2PbFnoCwFnTh',
                'created_at' => '2019-09-28 10:27:36',
                'updated_at' => '2019-09-28 10:27:36',
                'is_verified' => 'yes',
                'user_type' => 1,
                'plz' => NULL,
                'st_house' => NULL,
            ),
            1 => 
            array (
                'id' => 10,
                'name' => 'Hashim',
                'email' => 'hashim@hmail.com',
                'phone_number' => '090078701',
                'fcm_id' => NULL,
                'password' => '$2y$10$OmuaV.Q0YxpfnsCqxRwCEu02UByVvX0DpY5U6jONLEifpwm7zOf1a',
                'remember_token' => NULL,
                'created_at' => '2019-10-17 19:38:20',
                'updated_at' => '2019-10-17 19:39:11',
                'is_verified' => 'yes',
                'user_type' => 0,
                'plz' => 'llz',
                'st_house' => 'St',
            ),
            2 => 
            array (
                'id' => 13,
                'name' => 'Michael Thomas Smejkal',
                'email' => 'mts-berlin@gmx.de',
                'phone_number' => '017630145677',
                'fcm_id' => NULL,
                'password' => '$2y$10$qL2luPv00NG2K9rhA4IUfu/U70eKo2t4Q3iPcUfrAt5jbiXgX5jIq',
                'remember_token' => NULL,
                'created_at' => '2019-11-06 11:18:39',
                'updated_at' => '2020-02-18 15:24:59',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => '13125 Berlin',
                'st_house' => 'Lindenberger Weg 83',
            ),
            3 => 
            array (
                'id' => 14,
                'name' => 'William Pusch',
                'email' => 'fff@eu.xlm',
                'phone_number' => '0000',
                'fcm_id' => NULL,
                'password' => '$2y$10$ZTyuutUl2P.kGyyorODVPOeE1QmC72La.7OL4ezPGpWfSwkDQH.J2',
                'remember_token' => NULL,
                'created_at' => '2019-11-20 23:41:39',
                'updated_at' => '2019-11-20 23:49:17',
                'is_verified' => 'yes',
                'user_type' => 0,
                'plz' => '00000 Gießen',
                'st_house' => 'Test 12',
            ),
            4 => 
            array (
                'id' => 15,
                'name' => 'Rudolf Pusch',
                'email' => 'rudolf.pusch@hotmail.de',
                'phone_number' => '015117876712',
                'fcm_id' => NULL,
                'password' => '$2y$10$ESieRn2WjjN6ngTJjPygMuFuR8BXC9HwIp.f3aU25hEuQU8S6XAdC',
                'remember_token' => NULL,
                'created_at' => '2019-11-21 16:33:12',
                'updated_at' => '2019-11-25 14:00:44',
                'is_verified' => 'yes',
                'user_type' => 0,
                'plz' => '35390 Gießen',
                'st_house' => 'Dürerstr. 9',
            ),
            5 => 
            array (
                'id' => 16,
                'name' => 'Abdul',
                'email' => 'hashim@gmail.com',
                'phone_number' => '03001234567',
                'fcm_id' => NULL,
                'password' => '$2y$10$HL4S./52xcKcGvX0RjU6LOAsd/dRH4lNSe0ttCUtneQOJ/RKkiBIC',
                'remember_token' => NULL,
                'created_at' => '2019-11-24 00:50:39',
                'updated_at' => '2019-11-24 12:09:24',
                'is_verified' => 'yes',
                'user_type' => 0,
                'plz' => 'Lahore',
                'st_house' => 'main st',
            ),
            6 => 
            array (
                'id' => 17,
                'name' => 'Tanja Bader',
                'email' => 't.bader@elysius.eu',
                'phone_number' => '01746740231',
                'fcm_id' => NULL,
                'password' => '$2y$10$J19N0EYuZvceU9V4cJGRXeOjhF6.6U2dIXKFxLED9t/EDrmLTQeI.',
                'remember_token' => NULL,
                'created_at' => '2019-11-25 20:44:34',
                'updated_at' => '2019-11-25 20:45:05',
                'is_verified' => 'yes',
                'user_type' => 0,
                'plz' => '64546 Mörfelden-Walldorf',
                'st_house' => 'Soonwaldstr. 2',
            ),
            7 => 
            array (
                'id' => 18,
                'name' => 'kashif',
                'email' => 'ap@gmail.com',
                'phone_number' => '3764646',
                'fcm_id' => NULL,
                'password' => '$2y$10$ER13ijKA/dJxtlcw1xObrORWCHqk16nWvMAIy/z75k3F79BdesXXq',
                'remember_token' => NULL,
                'created_at' => '2020-01-19 20:14:07',
                'updated_at' => '2020-01-19 20:14:07',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => 'hdhs',
                'st_house' => 'djdh',
            ),
            8 => 
            array (
                'id' => 21,
                'name' => 'Stephan Balling',
                'email' => 's.balling@elysius.eu',
                'phone_number' => '0176/21812485',
                'fcm_id' => NULL,
                'password' => '$2y$10$OePkrH97QfE0HbV1wiMZa.KXSrZnvbSTN1azRfnIqThUbPca.Mmxq',
                'remember_token' => NULL,
                'created_at' => '2020-03-03 17:40:22',
                'updated_at' => '2020-03-03 17:40:28',
                'is_verified' => 'yes',
                'user_type' => 0,
                'plz' => '81929 München',
                'st_house' => 'Burgauerstr. 61',
            ),
            9 => 
            array (
                'id' => 22,
                'name' => 'yg',
                'email' => 'iftihussain4u@gmail.com',
                'phone_number' => '03005411085',
                'fcm_id' => NULL,
                'password' => '$2y$10$h2iBofDLkWDRTd/DeYsjkOrmFDGT4.wV8CTM3yZHFRCI2sg/ZmqYy',
                'remember_token' => NULL,
                'created_at' => '2020-03-12 15:33:00',
                'updated_at' => '2020-03-12 15:33:00',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => 'jinnah',
                'st_house' => 'garden',
            ),
            10 => 
            array (
                'id' => 23,
                'name' => 'Abdur Rehman',
                'email' => 'sydabdrehman@gmail.com',
                'phone_number' => NULL,
                'fcm_id' => NULL,
                'password' => '$2y$10$9HFHY03tGNrf2jeZeakJoOlrrmLqjijgbE8WFjYHNMQf7y08JtVZa',
                'remember_token' => NULL,
                'created_at' => '2020-03-19 08:41:25',
                'updated_at' => '2020-03-19 08:41:25',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => NULL,
                'st_house' => NULL,
            ),
            11 => 
            array (
                'id' => 24,
                'name' => 'Abdur',
                'email' => 'sydabdurrehman2@gmail.com',
                'phone_number' => NULL,
                'fcm_id' => NULL,
                'password' => '$2y$10$cN7jOzLiPvOQ0qirIGox6ecqRf0RCBMlyQWaLFWczZmq3/LkFNWJG',
                'remember_token' => NULL,
                'created_at' => '2020-03-19 08:54:57',
                'updated_at' => '2020-03-19 08:54:57',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => NULL,
                'st_house' => NULL,
            ),
            12 => 
            array (
                'id' => 25,
                'name' => '123123',
                'email' => 'Muhammadkashif70001220@gmail.com',
                'phone_number' => NULL,
                'fcm_id' => NULL,
                'password' => '$2y$10$W7D1vJNSkL5pRn1h4mszTO0xWs9P2qcenKvCSlnoaUVro655ZLtZC',
                'remember_token' => NULL,
                'created_at' => '2020-03-19 09:06:08',
                'updated_at' => '2020-03-19 09:06:08',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => NULL,
                'st_house' => NULL,
            ),
            13 => 
            array (
                'id' => 26,
                'name' => 'asdsad',
                'email' => 'M2uhammadkashif700010@gmail.com',
                'phone_number' => NULL,
                'fcm_id' => NULL,
                'password' => '$2y$10$EJ8GdpruoKi4Z9udzzaTi.pAUDXRDi5wTcosd0nzgOPok.t8dlgSG',
                'remember_token' => NULL,
                'created_at' => '2020-03-19 09:13:04',
                'updated_at' => '2020-03-19 09:13:04',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => NULL,
                'st_house' => NULL,
            ),
            14 => 
            array (
                'id' => 27,
                'name' => '123123',
                'email' => '23Muhammadkashif700010@gmail.com',
                'phone_number' => NULL,
                'fcm_id' => NULL,
                'password' => '$2y$10$7Wy/9KRKOxFsGs4jcbdu8uyh5nutePPOtV5p0vOKExkolIZnEegY2',
                'remember_token' => NULL,
                'created_at' => '2020-03-19 09:13:55',
                'updated_at' => '2020-03-19 09:13:55',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => NULL,
                'st_house' => NULL,
            ),
            15 => 
            array (
                'id' => 28,
                'name' => '123123',
                'email' => '23Muhammadkashif700010@gmail.com3',
                'phone_number' => NULL,
                'fcm_id' => NULL,
                'password' => '$2y$10$2cU7JgH8JLLsPAdOLMZG1Onh1gUSbfrl4hYbJEFlUGObPtTmVDZlG',
                'remember_token' => 'nP98jrY5cca3fmRJHZTd8YTjA2WazFchtuqv3dvYDNFhlTID8o5vJnwDW04d',
                'created_at' => '2020-03-19 09:14:45',
                'updated_at' => '2020-03-19 09:14:45',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => NULL,
                'st_house' => NULL,
            ),
            16 => 
            array (
                'id' => 29,
                'name' => '123123',
                'email' => '3323Muhammadkashif700010@gmail.com3',
                'phone_number' => NULL,
                'fcm_id' => NULL,
                'password' => '$2y$10$RgRjsn0JAkoUu9htHFecCO2wCuXp9dzyNCi0eNjBQiU9dPFlqg2RG',
                'remember_token' => 'huuFtJiwFjh3vDdqOSL62L1VomXyYZBgnFjMLlO8XON95XZOvqiuOMKePRLy',
                'created_at' => '2020-03-19 09:15:22',
                'updated_at' => '2020-03-19 09:15:22',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => NULL,
                'st_house' => NULL,
            ),
            17 => 
            array (
                'id' => 30,
                'name' => 'Testing',
                'email' => 'syedabdurrehman@gmail.com',
                'phone_number' => NULL,
                'fcm_id' => NULL,
                'password' => '$2y$10$8pmGb85JZE1hEXfEZPtxf.2XHQUotfwMguN5KH7AS6.LkWMWdtDoK',
                'remember_token' => 'pWAlxSPUoehM0asV8iN9uTlxUwo1OMa5r6AHDe1X6UFzT87PayghBB9zeF4V',
                'created_at' => '2020-03-19 19:04:48',
                'updated_at' => '2020-03-19 19:04:48',
                'is_verified' => 'no',
                'user_type' => 0,
                'plz' => NULL,
                'st_house' => NULL,
            ),
        ));
        
        
    }
}